version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build complete.
  post_build:
    commands:
      - echo Build finished successfully.
artifacts:
  files:
    - '**/*'
